export const json = [
  {
    id: 0,
    isActive: false,
    name: 'Lynch Houston',
    gender: 'male',
    company: 'ROOFORIA',
    email: 'lynchhouston@rooforia.com',
  },
  {
    id: 1,
    isActive: false,
    name: 'Alexis Olsen',
    gender: 'female',
    company: 'QUILK',
    email: 'alexisolsen@quilk.com',
  },
  {
    id: 2,
    isActive: true,
    name: 'Stephens Leblanc',
    gender: 'male',
    company: 'RECOGNIA',
    email: 'stephensleblanc@recognia.com',
  },
  {
    id: 3,
    isActive: false,
    name: 'Hollie Norman',
    gender: 'female',
    company: 'ACRODANCE',
    email: 'hollienorman@acrodance.com',
  },
  {
    id: 4,
    isActive: true,
    name: 'Ophelia Conrad',
    gender: 'female',
    company: 'PORTALINE',
    email: 'opheliaconrad@portaline.com',
  },
];
